//
//  NetworkUrl.swift
//  TANetworkingSwift
//
//  Created by Girijesh Kumar on 09/01/16.
//  Copyright © 2016 Girijesh Kumar. All rights reserved.
//

import Foundation
import UIKit

/** --------------------------------------------------------
* HTTP Basic Authentication
*	--------------------------------------------------------
*/
let kAgoraAppId                 = "7190d23ee4f5432998d03def0da38805"
let kNetworkErrorAlert          = "Network error. Check your network connections and try again."
let kMale                       = "1"
let kFemale                     = "2"
let kOther                      = "3"
let kHTTPUsername               = ""
let kHTTPPassword               = ""




//let kDeviceType               = "ios" //1-iOS 2- Andoid
let OS                          = UIDevice.current.systemVersion
let kAppVersion                 = "1.0"
let kDeviceModel                = UIDevice.current.model
//let kSemiBoldFont             = UIFont.init(name: "SourceSansPro-Semibold", size: 14.0)
let kRegularFont                = UIFont.init(name: "semi-regular", size: 14.0)
//let kAPIKEY                   = "cesar@123"
//let CLASS_START               = print(__FILE__)
let kResult                     = "result"
let kDefaultApiCurrency         = "INR"
let kDefaultApiCurrencyValue    = "1.00000"
let kDefaultCurrencySymbol      = "₹"

//kDefaultApiCurrency kDefaultApiCurrencyValue
/** --------------------------------------------------------
*	 API Base URL defined by Targets.
*	--------------------------------------------------------
*/

let kBASEURL                      = "https://www.wemsrsa.com/api/"
let kImageBaseUrl               = "http://3.16.96.108:3000/"

let kImageBaseUrl2              = "http://amonewyork.com/Images/CoverPic/"
let kImageBaseUrl3              = "http://amonewyork.com//Images/MultiPic/"
let kVideoBaseUrl               = "http://moneyforlikes.com/assets/videos/postVideos/"
let kAudioBaseUrl               = "http://moneyforlikes.com/assets/audio/"

let kSelectYesNo                = ["Yes","No"]
let kSelectGender               = ["Male", "Female", "Unisex"]
let kAddressType                = ["Electricity Bill", "Telephone Bill","Piped Gas Bill", "Water", "Postpaid Mobile Phone Bills", "Bank Account Statements"]
let kAccountTypeArr             = ["Saving Account","Current Account"]
let kSelectDay                  = ["Sunday", "Monday", "Tuesday","Wednesday","Thursday","Friday","Saturday"]
let kSelectConsultantType       = ["Astrologer", "Relationship Counseller"]
let kSelectMerritalStatus       = ["Married", "Unmarried"]
let kSWRevealViewController     = "SWRevealViewController"

let kAuthentication             = "Authentication"          //Header key of request  encrypt data
let kEncryptionKey              = ""                    //Encryption key replace this with your projectname

let kAllPost                     = "-1"
let kFacebookPost                = "1"
let kInstagramPost               = "2"
let kMFLPost                     = "3"
let kPageOne                     = "1"
let kPageTwo                     = "2"
let kPageThree                   = "3"
let kPageFour                    = "4"
let kMFLType                     = "3"
let kFacebookAccountType         = "1"
let kInstagramAccountType        = "2"
let kMFLAccountType              = "3"
let kStripLivePublishKey         = "pk_live_aWtIrDz1lyoLQoXfrP4LpZaW" // pk_test_CDaxip2f9HfFFnTJa8XTSRjW
let kStripTestPublishKey         = "pk_test_FQ00wxSQ93Gb1dx114CDTBTm00QFTwALCJ"
let kViewType                   = "1"
let kLikesType                  = "0"
let kInstagramClientId          = "b584003ff84949a0bf7a6f022a92afbb"
let kINSTAGRAM_AUTHURL          = "https://api.instagram.com/oauth/authorize/"
let kINSTAGRAM_APIURL           = "https://api.instagram.com/v1/users/"
let kINSTAGRAM_CLIENTSERCRET    = "982ea11972424126a2ff4961fb082210"
let kINSTAGRAM_REDIRECT_URL     = "https://www.adixsoft.com/"
let kINSTAGRAM_ACCESS_TOKEN     =  "access_token"
let kINSTAGRAM_SCOPE            = "likes+comments+relationships"
let kIGPostTitle                = "IG Post"
let kIGPostDescription          = "IG Post Description"
let kDefaultsContact            = "12345"
let mapbox_access_token         = "pk.eyJ1IjoiYWxnb3NvZnRtYW5vaiIsImEiOiJjazlzbzh1YWkxNmJ1M2dxaDA4eHo1aWg3In0.ktk7NRGkg1eJeQ0iK97XBg"
let mapbox_api                  = "https://api.mapbox.com/geocoding/v5/mapbox.places/"
//#if DEBUG
//    static int ddLogLevel = LOG_LEVEL_VERBOSE;
//    #elif TEST
//    static int ddLogLevel = LOG_LEVEL_INFO;
//    #elif STAGE
//    static int ddLogLevel = LOG_LEVEL_WARN;
//    #else
//    static int ddLogLevel = LOG_LEVEL_ERROR;
//    #endif

    /*****************************************************************************/
    /* Entry/exit trace macros                                                   */
    /*****************************************************************************/
   // #define TRC_ENTRY()    DDLogVerbose(@"ENTRY: %s:%d:", __PRETTY_FUNCTION__,__LINE__);
   // #define TRC_EXIT()     DDLogVerbose(@"EXIT:  %s:%d:", __PRETTY_FUNCTION__,__LINE__);
    
    
/** --------------------------------------------------------
*		Used Web Services Name
*	--------------------------------------------------------
*/
//postList postDetails , connectionList
let kServices                   = "services"
let kName                       = "name"
let kFirst_name                 = "first_name"
let kLast_name                  = "last_name"
let kMobile_number              = "mobile_number"
let kDate_of_birth              = "date_of_birth"
let kTime_of_birth              = "time_of_birth"
let kPlace_of_birth             = "place_of_birth"
let kMerital_status             = "merital_status"
let kEmployment_in              = "employment_in"
let kLanguage                   = "language"
let kExperience                 = "experience"
let kHome                       = "Home"
let kLoginStoryboard            = "Login"
let kLogin                      = "login"
let kRecievedUserId             = "recievedUserId"
let kPostTransactionHistory     = "postTransactionHistory"
let kWalletTransactionHistory   = "walletTransactionHistory"
let kShowWalletAmount           = "walletAmount"
let kAmount                     = "amount"
let kOnlinePortal               = "onlinePortal"
let kStripeAccessToken          = "token"
let kAddMoney                   = "addMoney"
let kConnection                 = "connectionList"
let kSocialLogin                = "socialLogin"
let kPostView                   = "view"
let kPostViewApi                = "PostViews"
let kPostLikes                  = "postLikes"
let kloginData                  = "loginData"//loginData
let kGetExpertiseList           = "common/getExpertiseList"
let kLogout                     = "logout"
let kUpdateProfile              = "updateProfile"
let kGetProfile                 = "getProfile"
let kCategoryList               = "categoryList"
let kQuestionList               = "questionList"
let kGetAstrologerEarnings      = "astrologer/getAstrologerEarnings"
let kGetAstrologerPayouts       = "astrologer/getAstrologerPayouts"
let kGetAstrologerCustomers     = "astrologer/getAstrologerCustomers"
let kGetAstrologerReviews       = "astrologer/getAstrologerReviews"
let kGetAstProfileCompleteStatus = "astrologer/getAstrologerProfileCompleteStatus"
let kGetAstrologerSechedulerData = "astrologer/getAstrologerSechedulerData"
let kSetAstrologerSechedulerData = "astrologer/setAstrologerSechedulerDataApp"
let kGetCustomNotifications      = "common/getCustomNotifications"
let kDeleteAstSechedulerDataApp  = "astrologer/deleteAstrologerSechedulerDataApp"
let kGetReportCommunicationHistory = "astrologer/getReportCommunicationHistory"
let kSetAstrologerOnlineStatus  = "astrologer/setAstrologerOnlineStatus"
let kSendReportMessage          = "customer/sendReportMessage"
let kGetReportHistoryDetails    = "astrologer/getReportHistoryDetails"
let kSetAstReportFilesData      = "astrologer/setAstrologerReportFilesData"
let kGetReportsList             = "general/getReportsList"
let kWeeklyPostList             = "weeklyPost"
let kPostDetails                = "postDetails"
let kPostId                     = "postId" //postLikesUserId
let kPostLikesUserId            = "postUserId"
let kcreateAccout               = "register"
let kReply                      = "reply"
let kAddPost                    = "addPost"
let kGetProfileData             = "astrologer/getProfileData"
let kSetLanguageData            = "astrologer/setLanguageData"
let kSetProfileData             = "astrologer/setProfileData"
let kSetBirthDetailsData        = "astrologer/setBirthDetailsData"
let kSetLogin                   = "astrologer/setLogin"
let kSetAstrologerAboutData     = "astrologer/setAstrologerAboutData"
let kSetAstrologerLocationData  = "astrologer/setAstrologerLocationData"
let kSetReviewReply             = "astrologer/setReviewReply"
let kSetAstrologerExperienceData = "astrologer/setAstrologerExperienceData"
let kGetAstrologerExpertiseData = "astrologer/getAstrologerExpertiseData"
let kGetAstrologerLanguageData  = "astrologer/getAstrologerLanguageData"
let kSetAstrologerProfileData   = "astrologer/setAstrologerProfileData"
let kSetLogout                  = "astrologer/setLogout"
let kGetLanguageList            = "common/getLanguageList"
let kGetReportsDetails          = "general/getReportsDetails"
let kSetProfileImageData        = "astrologer/setProfileImageData"
let kGetAstrologerPancardData   = "astrologer/getAstrologerPancardData"
let kGetAstrAfterLoginHomePage  = "forapp/gereral/getAstrologerAfterLoginHomePage"
let kSetAstrologerIdProofData   = "astrologer/setAstrologerIdProofData"
let kGetHomePageSecondPartData  = "forapp/getHomePageSecondPartData"
let kGetAstrologersDetails      = "general/getAstrologersDetails"
let kGetServicesList            = "general/getServicesList"
let kGetHoroscopeList           = "general/getHoroscopeList"
let kGetAstProfileReportData    = "astrologer/getAstrologerProfileReportData"
let kSetAstProfileReportData    = "astrologer/setAstrologerProfileReportData"
let kGetAstrologersList         = "general/getAstrologersList"
let kGetAstrologerBankData      = "astrologer/getAstrologerBankData"
let kSetAstrologerBankData      = "astrologer/setAstrologerBankData"
let kGetWalletData              = "astrologer/getWalletData"
let kSetReportPaymentInitialize = "astrologer/setReportPaymentInitialize"
let kGetPaymentGetwayList       = "common/getPaymentGetwayList"
let kSetReportPaymentCompleted  = "astrologer/setReportPaymentCompleted"
let kSetPaymentCompleted        = "astrologer/setPaymentCompleted"
let kSetPaymentInitialize       = "astrologer/setPaymentInitialize"
let kGetPackagesList            = "common/getPackagesList"
let kGetCouponList              = "common/getCouponList"
let kSetForgotPassword          = "astrologer/setForgotPassword"
let kPutSignupForm              = "astrologer/putSignupForm"
let kGetCountryCodeList         = "common/getCountryCodeList"
let kGetTimeZoneList            = "common/getTimeZoneList"
let kSetResetPassword           = "astrologer/setResetPassword"
let kResendVerificationCode     = "astrologer/resendVerificationCode"
let kPutAccountVerification     = "astrologer/putAccountVerification"
let kGetReportHistoryData       = "astrologer/getReportHistoryData"
let kApiKey                     = "Apikey"
let kApiDate                    = "Apidate"
let kApiKeyValue                = "fc6523638a98b919b37364116a3ebca8"
let kApiDateValue               = "2019-11-19"
let kApilanguage                = "Apilanguage"//en
let kApitimezone                = "Apitimezone" //":"Asia/Kolkata",
let kApidevicetype              = "Apidevicetype"//":"IOS",
let kIOS                        = "IOS"
let kApidevicelat               = "Apidevicelat"
let kApidevicelong              = "Apidevicelong"
let kApideviceid                = "Apideviceid"
let kApicurrdate                = "Apicurrdate"//"2020-10-15",
let kApicurrtime                = "Apicurrtime"//"1602745108",
let kApitoken                   = "Apitoken"
let kDefaultLanguage            = "en"
let kDefaultApiTimeZone         = "Asia/Kolkata"
let kApicurrency                = "Apicurrency"
let kApicurrencyvalue           = "Apicurrencyvalue"

let kBrandList                  = "brandlist"
let kCategory                   = "category"
let kFilter                     = "filter"
let kMalls                      = "malls"
let kStore                      = "store"
let kMalloffers                 = "malloffers"
let kStoreoffer                 = "storeoffer"
let kBrandOffer                 = "brandoffer"
let kMap                        = "map"
let kCatloguetag                = "Catloguetag"
let kTag                        = "tag"
let kTagDetial                  = "tagDetial"
let kSerchRetailer              = "serchRetailer"
let kSignup                     = "signup"
let kPurchasedCourse            = "purchasedCourse"
let kHomePage                   = "homePage"
let kSubscriptionStatus         = "subscriptionStatus"
let kPurchasedCourseVideo       = "purchasedCourseVideo"
let kPurchasedCourseVideoDetail = "purchasedCourseVideoDetail"
let kUpdateVideoLastSeen        = "updateVideoLastSeen"
let kListInstructorCourses      = "listInstructorCourses"
let kListEventInstructor        = "listEventInstructor"
let kViewCourse                 = "viewCourse"
let kViewEvent                  = "viewEvent"
let kSubscriptionDetail         = "subscriptionDetail"
let kFinalPayment               = "final-payment"
let ksubscriptionPaymentFinal   = "subscription-payment-final"
let kCreatePaymentIntent        = "create-payment-intent"
let kSubscriptionPaymentIntent  = "subscription-payment-intent"
let kCreateOrder                = "createOrder"
let kListInstructor             = "listInstructor"
let kListEvent                  = "listEvent"
let kVerifyOtp                  = "verifyOtp"
let kLike                       = "like"
let kNotificationhistory        = "notificationhistory"
let kNotification               = "notification"
let kFullName                   = "fullname"
let kMobileNumber               = "mobileNumber"
let kAllNews                    = "allNews"
let kAboutBliss                 = "about"


let kAuthorization             = "Authorization"
 


let kForgotPassword             = "forgotPassword"
/** --------------------------------------------------------
*		API Request & Response Parameters Keys
*	--------------------------------------------------------
*/


let kPhoneCode                  = "phoneCode"
let kAltMobileCode              = "altMobileCode"
let kAltMobileNumber            = "altMobileNumber"
let kConsultantType             = "consultantType"
let kCallRate                   = "callRate"
let kChatRate                   = "chatRate"
let kReportRate                 = "reportRate"
let kLocalTime                  = "date_created"
let kAddress                    = "address"
let kCurrency_code              = "currency_code"
let kReport_wallet_amount       = "report_wallet_amount"
let kReport_last_name           = "report_last_name"
let kReport_gender              = "report_gender"
let kReport_birth_place         = "report_birth_place"
let kReport_birth_country       = "report_birth_country"
let kReport_partner_name        = "report_partner_name"
let kReport_partner_birth_date  = "report_partner_birth_date"
let kReport_partner_birth_time  = "report_partner_birth_time"
let kReport_partner_birth_place = "report_partner_birth_place"
let kReport_partner_birth_country = "report_partner_birth_country"
let kContactNumber              = "contactNo"
let kPageNumber                 = "pageNo"
let kPostType                   = "postType"
let kType                       = "type"
let kResendEditVerificationCode = "astrologer/resendEditVerificationCode"
let kAstrologerEmailMobileVerification  = "astrologer/astrologerEmailMobileVerification"
let kResetPassword              = "reset_password"
let kPostDescription            = "postDescriptions"
let kOtp                        = "getotp"
let kAstrologer_id              = "astrologer_id"
let kCustomer_id                = "customer_id"
let kCountry_id                 = "country_id"
let kAst_short_description_en   = "astrologer_short_description_en"
let kAst_short_description_hi   = "astrologer_short_description_hi"
let kAast_long_description_en   = "astrologer_long_description_en"
let kAst_long_description_hi    = "astrologer_long_description_hi"
let kAstrologer_video           = "astrologer_video"
let kAstrologer_address         = "astrologer_address"

let kLongDecsEnglish            = "longDecsEnglish"
let kLongDecsHindi              = "longDecsHindi"
let kUser_token                 = "user_token"
let kAstrologer_select_id       = "astrologer_select_id"
let kStart_date                 = "start_date" 
let kEnd_date                   = "end_date"
let kAst_current_status         = "astrologer_current_status"
let kAstrologer_schedules       = "astrologer_schedules"
let kFrom_user_id               = "from_user_id"
let kFrom_user_type             = "from_user_type"
let kTo_user_type               = "to_user_type"
let kTo_user_id                 = "to_user_id"
let kAstrologer_email_mobile    = "astrologer_email_mobile"
let kData_type                  = "data_type"
let kSchedule_id                = "schedule_id"
let kAdmin_approval_type        = "admin_approval_type"
let kPancard_number             = "pancard_number"
let kAadharcard_number          = "aadharcard_number"
let kAstr_proof_address_type    = "astrologer_proof_address_type"
let kAstrologer_experience      = "astrologer_experience"
let kExpertise_id               = "expertise_id"
let kAstrologer_working_portal  = "astrologer_working_portal"
let kReport_id                  = "report_id"
let kPackage_id                 = "package_id"
let kLanguage_id                = "language_id"
let kPackage_amount             = "package_amount"
let kResend_type                = "resend_type"
let kTransaction_id             = "transaction_id"
let kPurchase_id                = "purchase_id"
let kPackage_gst                = "package_gst"
let kPackageTotalAmount         = "package_total_amount"
let kPackagePayAmount           = "package_pay_amount"
let kVerification_type          = "verification_type"
let kVerification_code          = "verification_code"
let kPackage_talktime           = "package_talktime"
//let kPayment_type               = "payment_type"
let kastrologer_primary_lang_id   = "astrologer_primary_language_id"
let kastrologer_secondary_lang_id = "astrologer_secondary_language_id"
let kAsto_forgot_Code           = "astrologer_forgot_password_code"
let kMobile_otp                 = "astrologer_mobile_verification_code"//astrologer_id, astrologer_mobile_verification_code,
let kEmail_otp                  = "astrologer_email_verification_code"
let kOtpVerify                  = "verify_otp"
//let kName                       = "fName"
let kLastname                   = "lName"
let kPaymentCustName            = "name"
let kInstructorId               = "instructorId"
let kEmail                      = "email"
let kUserId                     = "userId"
let kUser_id                    = "user_id"
let kVideoId                    = "videoId"
let kLastSeen                   = "lastSeen"
let kCategoryId                 = "categoryId"
let kOtpkey                     = "otp"
let kUsername                   = "username"
let kAstrologer_name_en         = "astrologer_name_en"
let kAstrologer_name_hi         = "astrologer_name_hi"
let kAstrologer_mobile_code     = "astrologer_mobile_code"
let kAstrologer_mobile          = "astrologer_mobile"
let kAstrologer_email           = "astrologer_email"
let kAstrologer_gender          = "astrologer_gender"
let kCouponCode                 = "coupon_code"
let kCurrencyCode               = "currency_code"
let kPerpageData                = "perpageData"
let kReview_id                  = "review_id"
let kBirth_date                 = "birth_date"
let kBirth_time                 = "birth_time"
let kBirth_place                = "birth_place"
let kPageNo                     = "pageNo"
//let kAstrologer_id              = "astrologer_id"
let kMessage                    = "message"
let kSocialType                 = "socialType"
let kSocialId                   = "socialId"
let kPassword                   = "password"
let kConfPassword               = "confPassword"
let kCategories                 = "categories"
let kQuestions                  = "questions"
let kDeviceIp                   = "deviceIp"
let kDeviceToken                = "deviceToken"
let kLat                        = "lat"
let kLong                       = "long"
//let kDeviceType                 = "deviceType"
let kAstrologer_password        = "astrologer_password"
let kUsermobileEmail            = "userEmail"
let kService_id                 = "service_id"
let kReport_files_count         = "report_files_count"
let kReport_amount              = "report_amount"
let kReport_payable_amount      = "report_payable_amount"
let kReport_gst_amount          = "report_gst_amount"
let kReport_paid_amount         = "report_paid_amount"
let kReport_first_name          = "report_first_name"
let kReport_mobile_code         = "report_mobile_code"
let kReport_mobile              = "report_mobile"
let kReport_birth_date          = "report_birth_date"
let kReport_birth_time          = "report_birth_time"
let kReport_marital_status      = "report_marital_status"
let kReport_employed            = "report_employed"
let kReport_language            = "report_language"
let kPartners_details           = "partners_details"
let kReport_comment             = "report_comment"
let kPayment_type               = "payment_type"
let kConPassword                = "confirmpassword"
let kAstrologer_country         = "astrologer_country"
let kAstrologer_timezone        = "astrologer_timezone"
let kNewPassword                = "newpassword"
let kAccountType                = "account_type"
let kDeviceType                 = "deviceType"
let kToken                      = "token"
let kBusinessName               = "businessName"
let kRegistrationStatus         = "registrationStatus"
let kUserTypeN                  = "userType"
let kOffer                      = "offer"//**************
let kUserName                   = "EmailID" //**************
let kUserTypeId                 = "UserTypeId"
let kUserType                   = "Type"
let kEntryBy                    = "EntryBy"
let kBookingDescription         = "Description"
let kGigPricePerHour            = "GigPricePerHour"
let kEnquiryDatetime            = "EnquiryDatetime"
let kToUserId                   = "ToUserId"


let kFirstName                   = "firstName" //**************
let kEmail_Id                    = "EmailId" //**************
let kUPassword                   = "UPassword" //**************
let kCPassword                   = "CPassword" //**************
let kMobileNo                   = "MobileNo" //**************

let kLastName                    = "lastName" //**************
let kRid                        = "rid" //**************
let kLoginPassword                   = "UPassword" //**************
let kDeviceId                   = "deviceid" //**************
let kFIRSTNAME                  = "UL_FIRSTNAME"
let kLASTNAME                   = "UL_LASTNAME"
let kUSERNAME                   = "UL_USERNAME"
let kPASSWORD                   = "UL_PASSWORD"
let kMOBILE                     = "UL_MOBILE"
let kAreaCode                     = "AreaCode"
let kISADMIN                    = "UL_ISADMIN"
let kACTIVE                     = "UL_ACTIVE"
let kACCESSID                   = "UL_ACCESSID"
let kUNIQUEID                   = "UL_UNIQUEID"
let kULID                       = "UL_ID"
let kOffset                     = "offset"
let kImgId                      = "imgId"
let kLandmark                   = "landMark"
let kCountry                    = "country"
let kIndustry                   = "industry"
let kAboutMe                    = "aboutMe"
let kFacebook                   = "facebook"
let kTwitter                    = "twitter"
let kLinkedin                   = "linkedin"
let kDob                        = "dob"



let kWebsite                    = "website"
let kCountryName                = "countryName"
let kBusinessOpen               = "businesOpen"
let kBusinessClose              = "businessClose"
let kLunchStart                 = "lunchStart"
let kLunchClose                 = "lunchClose"
let kDaysOpen                   = "daysOpen"
let kPriceList                  = "priceList"
let kClipazName                 = "clipazName"
let kExpertise                  = "expertise"
let kStartTime                  = "startTime"
let kEndTime                    = "endTime"
let kSortBy                     = "sortBy"
let kAppointmentId              = "appointmentId"
let kClipazId                   = "clipazId"
let kSelectedTime               = "selectedTime"
let kastrologerId                 = "astrologerId"
let kServiceAmount              = "serviceAmount"
let kAppointmentTime            = "appointmentTime"
let kClipazImage                = "clipazImage"
let kastrologerName               = "astrologerName"
let kastrologerPic                = "astrologerPic"
let kServiceName                = "serviceName"
let kIsEditable                 = "isEditable"
let kGrowth                     = "growth"
let kPercentage                 = "percentage"
let kTotalAmount                = "totalAmount"
let kTotalBooking               = "totalBooking"
let kBookings                   = "bookings"
let kIstVisit                   = "istVisit"
let kTrimspirationImg           = "trimspirationImg"
let kCutTime                    = "cutTime"
let kPrice                      = "price"
let kProfilePicture             = "profilePic"
let kOldPin                     = "oldPin"
let kCurrentPin                 = "currentPin"

let kPostTitle                  = "postTitle"
let kDateOfBirth                = "dateOfBirth"
let kAstrologer_date_of_birth   = "astrologer_date_of_birth"
let kAstrologer_report_rate     = "astrologer_report_rate"
let kAstrologer_talk_rate       = "astrologer_talk_rate"
let kAstrologer_chat_rate       = "astrologer_chat_rate"
let kAstrologer_consultent_type = "astrologer_consultent_type"
let kTimeOfBirth                = "timeOfBirth"
let kPlaceOfBirth               = "placeOfBirth"
let kCountryOfBirth             = "countryOfBirth"
let kMerritalStatus             = "merritalStatus"
let kEmployment                 = "employment"
let kDate                       = "date"
let kGender                     = "gender"
let kCountryCode                = "countryCode"
let kWork                       = "work"
let kSchool                     = "school"
let kSkills                     = "skills"
let kCauses                     = "causes"
let kIntroduction               = "introduction"
let kAccount                    = "account"
let kAccount_Number             = "account_number"
let kAccount_Type               = "account_type"
let kIFSC_code                  = "ifsc_code"
let kAccount_holder_name        = "account_holder_name"
let kBank_name                  = "bank_name"
let kParams                     = "params"
let kAccess_token               = "access_token"
let kDevice_type                = "device_type"
//let kDeviceId                   = "device_id"
let kRegistrationId             = "registration_id"
let kOauth_token                = "oauth_token"
let kOauth_token_secret         = "oauth_token_secret"
let kMedia                      = "media"
let kMediaType                  = "media_type"
let kVideoThumbnail             = "video_thumbnail"
let kFrom_user                  = "from_user"
let kTo_user                    = "to_user"
let kIsEmailVerified            = "is_email_verified"
let kMediaFiles                 = "media_files"

let kIsInstagramConnected       = "is_instagram_connect"
let kIsSocialRegister           = "is_social_register"
let kInQueue                    = "in_queue"
let kIsReport                   = "is_report"
let kPushNotification           = "push_notification"
let kSound                      = "sound"
let kInterestedIn               = "interested_in"
let kIsFacebookConnected        = "is_facebook_connect"
let kId                         = "id"
let KCommentCount               = "comment_count"
let kPartyLocation              = "party_location"
let kMembers                    = "members"
let kCurrency                   = "currency"
let kPayment_id                 = "payment_id"
let kPayment_status             = "status"
let kStripePaymentId            = "stripePaymentId"
let kCourse_id                  = "course_id"
let kTotal_price                = "total_price"
let kOrder_id                   = "order_id"

let kAllFollowing               = "all_following"
let kTitle                      = "title"
let kRepetitionType             = "repetition_type"
let kPartyType                  = "party_type"
let kBeacon                     = "beacon"
let kMaximumDistance            = "max_distance"
let kPreferences                = "preferences"
let kMinimumAge                 = "min_age"
let kMaximumAge                 = "max_age"
let kLocation                   = "location"
let kIsProfilePicture           = "is_profile_picture"
let kRadius                     = "radius"
let kRequestId                  = "request_id"

let kNext                       = "next"
let kResults                    = "results"
let kUrl                        = "url"
let kCreatedAt                  = "created_at"
let kCreatedBy                  = "created_by"
let kModifiedAt                 = "modified_at"
let kModifiedAtLt               = "modified_at_lt"
let kModifiedAtGt               = "modified_at_gt"
let kEmbedded                   = "_embedded"
let kOwner                      = "owner"
let kBackgroundImage            = "background_image"
let kPartyMember                = "party_member"
let kParty                      = "party"
let k_Id                        = "_id"
let kIsReported                 = "is_report"
let kMediafiles                 = "media_files"
let kMember                     = "member"

let kPartyOccurence             = "party_occurence"
let kSender                     = "sender"
let kReceiver                   = "receiver"
let kInvitedUsers               = "invited_users"
let kPartyMembers               = "party_members"
let kGuestUsers                 = "guest_users"
let kDateSocialImage            = "dateSocialImage"
let kFacebookArr                = "facebookArr"
let kInstagramArr               = "instagramArr"
let kSearch                     = "search"
let kCity                       = "city"
